resolver: lts-20.23

packages:
  - .

extra-deps:
  - git: https://github.com/jasagredo/tree-diff
    commit: a97c7ab0792efee192a11d693cef69801c0fb280

allow-newer: true

nix:
  enable: false
  pure: false
  packages: [zlib]
